import { useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { ArrowLeft, CarFront, CheckCircle2, ChevronDown, FileSearch, ImageUp, MapPin, MessageCircle, PackageCheck, Search, ShieldCheck, Truck, Upload, UserRound, Wrench } from "lucide-react";
import StoreLayout, { PageSection, SectionTitle, whatsapp } from "@/components/StoreLayout";

type Part = { id: number; title: string; oem: string; model: string; category: string; price: string; stock: string; image: string; source: string };
const parts: Part[] = [
  { id: 1, title: "تيل فرامل أمامي — توسان NX4", oem: "58101-D3A00", model: "توسان", category: "فرامل وعفشة", price: "2,450 ج.م", stock: "متوفر · 6 قطع", image: "/manus-storage/tucson_0380ba3b.jpg", source: "موبيس أصلي" },
  { id: 2, title: "فلتر زيت أصلي — إيلانترا CN7", oem: "26300-2M000", model: "إيلانترا", category: "محرك", price: "580 ج.م", stock: "متوفر · 18 قطعة", image: "/manus-storage/elantra-cerato_4969652e.jpg", source: "غبور مصر OEM" },
  { id: 3, title: "سير مجموعة — سبورتاج NQ5", oem: "25212-2U000", model: "سبورتاج", category: "محرك", price: "1,180 ج.م", stock: "متوفر · 4 قطع", image: "/manus-storage/sportage_a48428ed.jpg", source: "موبيس أوروبا" },
  { id: 4, title: "حساس كرنك — كيا سيراتو K3", oem: "39180-2B000", model: "سيراتو", category: "كهرباء وحساسات", price: "1,350 ج.م", stock: "متوفر · 3 قطع", image: "/manus-storage/elantra-cerato_4969652e.jpg", source: "موبيس أصلي" },
];
const cars = [{ name: "توسان", english: "Hyundai Tucson", generation: "NX4 / TL", count: "1,280 قطعة", image: "/manus-storage/tucson_0380ba3b.jpg" }, { name: "سبورتاج", english: "Kia Sportage", generation: "NQ5 / QL", count: "980 قطعة", image: "/manus-storage/sportage_a48428ed.jpg" }, { name: "إيلانترا", english: "Hyundai Elantra", generation: "HD / AD / CN7", count: "1,145 قطعة", image: "/manus-storage/elantra-cerato_4969652e.jpg" }, { name: "سيراتو", english: "Kia Cerato", generation: "K3 / Grand Cerato", count: "860 قطعة", image: "/manus-storage/elantra-cerato_4969652e.jpg" }];

function PartCard({ part }: { part: Part }) { return <article className="product-card" data-scroll-card><div className="product-image"><img src={part.image} alt={part.title} loading="lazy" width="640" height="420" /><span className="stock-badge"><i /> متوفر</span></div><div className="product-body"><div className="product-source"><span>{part.source}</span><span>{part.model}</span></div><h3>{part.title}</h3><div className="oem-line"><span>OEM</span><strong>{part.oem}</strong></div><div className="product-bottom"><div><strong>{part.price}</strong><small>{part.stock}</small></div><Link className="product-link" href={`/parts/${part.id}`} aria-label="تفاصيل المنتج"><ArrowLeft size={18} /></Link></div></div></article>; }
function ProductGrid({ items }: { items: Part[] }) { return <div className="products-grid">{items.map((part) => <PartCard part={part} key={part.id} />)}</div>; }

export function PartsPage() { const [query, setQuery] = useState(""); const [model, setModel] = useState("الكل"); const filtered = useMemo(() => parts.filter((part) => (model === "الكل" || part.model === model) && (!query || `${part.title} ${part.oem}`.toLowerCase().includes(query.toLowerCase()))), [model, query]); return <StoreLayout title="كتالوج قطع الغيار" eyebrow="01 / ابحث عن القطعة"><PageSection><div className="catalog-search"><Search size={20} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث برقم OEM أو وصف القطعة..." /><Link className="button button-primary" href="/oem-search">بحث متقدم</Link></div><div className="catalog-toolbar"><div className="filter-scroll">{["الكل", ...cars.map((car) => car.name)].map((item) => <button className={model === item ? "filter-chip active" : "filter-chip"} onClick={() => setModel(item)} key={item}>{item}</button>)}</div><span>{filtered.length} منتجات</span></div><ProductGrid items={filtered} /></PageSection></StoreLayout>; }

export function ProductPage() { const [, params] = useRoute<{ id: string }>("/parts/:id"); const part = parts.find((item) => item.id === Number(params?.id)) ?? parts[0]; return <StoreLayout title="تفاصيل القطعة" eyebrow="كتالوج / مطابقة OEM"><PageSection><div className="product-detail"><div className="detail-image"><img src={part.image} alt={part.title} /></div><div className="detail-copy"><span className="product-source">{part.source} · {part.model}</span><h2>{part.title}</h2><div className="detail-oem">OEM <strong>{part.oem}</strong></div><p>قطعة أصلية متوافقة مع الموديل الموضح. المطابقة النهائية تتم بعد مراجعة رقم الشاسيه قبل الشحن.</p><div className="detail-trust"><span><ShieldCheck size={17} /> مطابقة VIN</span><span><PackageCheck size={17} /> {part.stock}</span></div><strong className="detail-price">{part.price}</strong><div className="hero-ctas"><a className="button button-primary" href={whatsapp(`أريد طلب ${part.title} - رقم OEM ${part.oem}`)} target="_blank" rel="noreferrer"><MessageCircle size={18} /> اطلب عبر واتساب</a><Link className="button button-ghost" href="/cart">أضف للسلة</Link></div></div></div></PageSection><PageSection className="soft-section"><SectionTitle eyebrow="قطع مرتبطة" title="ممكن تحتاجها مع القطعة" /><ProductGrid items={parts.filter((item) => item.id !== part.id)} /></PageSection></StoreLayout>; }

export function CartPage() { return <StoreLayout title="سلة المشتريات" eyebrow="03 / راجع طلبك"><PageSection><div className="cart-layout"><div className="cart-list"><div className="cart-item"><img src={parts[0].image} alt={parts[0].title} /><div><span>موبيس أصلي · توسان</span><h3>{parts[0].title}</h3><strong>{parts[0].price}</strong><small>الكمية: 1 · متوفر</small></div><button>حذف</button></div><div className="cart-item"><img src={parts[1].image} alt={parts[1].title} /><div><span>غبور مصر OEM · إيلانترا</span><h3>{parts[1].title}</h3><strong>{parts[1].price}</strong><small>الكمية: 1 · متوفر</small></div><button>حذف</button></div><Link className="text-link" href="/parts">← متابعة التسوق</Link></div><aside className="summary-card"><h3>ملخص الطلب</h3><div><span>إجمالي القطع</span><strong>3,030 ج.م</strong></div><div><span>الشحن</span><strong>يحدد بعد التأكيد</strong></div><hr /><div className="summary-total"><span>الإجمالي المبدئي</span><strong>3,030 ج.م</strong></div><label>رقم الشاسيه VIN <input placeholder="اكتب VIN للمطابقة قبل الشحن" /></label><a className="button button-primary" href={whatsapp("مرحباً، أريد تأكيد طلب السلة وإرسال رقم الشاسيه") } target="_blank" rel="noreferrer">أرسل الطلب على واتساب <MessageCircle size={17} /></a><small>لن يتم تأكيد الطلب قبل مراجعة المطابقة مع فريق المبيعات.</small></aside></div></PageSection></StoreLayout>; }

export function LoginPage() { return <StoreLayout title="حسابك في المتجر" eyebrow="04 / تسجيل الدخول"><PageSection><div className="auth-card"><div className="auth-icon"><UserRound size={25} /></div><h2>أهلاً بك من جديد</h2><p>سجل دخولك لمتابعة الطلبات وحفظ السيارات والقطع التي تهمك.</p><button className="button button-primary" onClick={() => window.location.href = "/api/login"}>تسجيل الدخول</button><div className="auth-note"><ShieldCheck size={16} /> تسجيل آمن عبر حساب Shopify</div></div></PageSection></StoreLayout>; }

export function VehiclesPage() { return <StoreLayout title="اختار عربيتك" eyebrow="02 / مطابقة السيارة"><PageSection><SectionTitle eyebrow="الموديلات المتاحة" title="ابدأ من عربيتك" copy="اختار الموديل عشان نشوف لك القطع المناسبة حسب الجيل والسنة." /><div className="vehicle-grid">{cars.map((car, index) => <Link className="vehicle-card" href={`/models/${encodeURIComponent(car.name)}`} key={car.name}><img src={car.image} alt={car.english} /><div className="vehicle-overlay" /><div className="vehicle-index">0{index + 1}</div><div className="vehicle-info"><span>{car.english} · {car.generation}</span><strong>{car.name}</strong><small>{car.count} <ArrowLeft size={13} /></small></div></Link>)}</div></PageSection></StoreLayout>; }

export function OemSearchPage() { const [query, setQuery] = useState(""); const result = query ? parts.filter((part) => part.oem.toLowerCase().includes(query.toLowerCase())) : []; return <StoreLayout title="بحث برقم OEM" eyebrow="05 / بحث مباشر"><PageSection><div className="search-panel"><FileSearch size={30} /><h2>اكتب رقم القطعة الأصلي</h2><p>مثال: 58101-D3A00. سنعرض المطابقات الأقرب ونراجعها معك قبل الشحن.</p><div className="catalog-search"><input dir="ltr" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="58101-D3A00" /><button className="button button-primary">ابحث الآن</button></div></div>{result.length > 0 && <><SectionTitle eyebrow="نتيجة البحث" title="وجدنا لك" /><ProductGrid items={result} /></>}</PageSection></StoreLayout>; }

export function MatcherPage() { const [mode, setMode] = useState("وصف القطعة"); return <StoreLayout title="مساعد المصري الذكي" eyebrow="06 / ابحث بطريقتك"><PageSection><div className="matcher-page"><div><SectionTitle eyebrow="مش لازم تعرف اسم القطعة" title="قول لنا اللي عندك" copy="اكتب وصفك بالعامية أو رقم OEM أو ارفع صورة، وفريقنا يراجع لك النتيجة." /><div className="matcher-points"><div><CheckCircle2 size={17} /> يفهم وصفك بالعامية المصرية</div><div><CheckCircle2 size={17} /> يرشح رقم OEM مناسب</div><div><CheckCircle2 size={17} /> يطلب VIN قبل التأكيد</div></div></div><div className="matcher-widget glass-card"><div className="matcher-tabs">{["وصف القطعة", "رقم OEM", "صورة"].map((item) => <button className={mode === item ? "active" : ""} onClick={() => setMode(item)} key={item}>{item === "صورة" ? <ImageUp size={16} /> : <FileSearch size={16} />} {item}</button>)}</div>{mode === "صورة" ? <button className="upload-zone"><Upload size={26} /><strong>ارفع صورة القطعة</strong><span>PNG أو JPG</span></button> : <div className="matcher-input"><textarea placeholder={mode === "رقم OEM" ? "58101-D3A00" : "عايز تيل فرامل قدامي لتوسان 2019"} /><a className="button button-primary" href={whatsapp("مرحباً، أريد مساعدة من المساعد الذكي في تحديد قطعة") } target="_blank" rel="noreferrer">أرسل للتحليل <ArrowLeft size={17} /></a></div>}<div className="widget-disclaimer"><ShieldCheck size={14} /> المطابقة النهائية تتم بعد استلام رقم الشاسيه</div></div></div></PageSection></StoreLayout>; }

export function TrackingPage() { return <StoreLayout title="تتبع طلبك" eyebrow="07 / خدمة العملاء"><PageSection><div className="search-panel"><Truck size={30} /><h2>فين طلبك؟</h2><p>اكتب رقم الطلب أو رقم الهاتف وسيتواصل معك فريق المبيعات بالتحديث.</p><div className="catalog-search"><input placeholder="رقم الطلب أو رقم الهاتف" /><button className="button button-primary">تتبع الطلب</button></div><a className="text-link" href={whatsapp("مرحباً، أريد تتبع طلبي") } target="_blank" rel="noreferrer">أو اسألنا مباشرة على واتساب ←</a></div></PageSection></StoreLayout>; }

export function ContactPage() { return <StoreLayout title="تواصل معنا" eyebrow="08 / الحرفيين - السلام"><PageSection><div className="contact-grid"><div className="contact-copy"><SectionTitle eyebrow="المخزن وفريق المبيعات" title="خبرة المخزن في خدمتك" copy="ابعت لنا رقم الشاسيه أو صورة القطعة وسنساعدك في الوصول للمطابقة المناسبة." /><div className="contact-lines"><a href={whatsapp("مرحباً، أريد التواصل مع خبير قطع غيار") } target="_blank" rel="noreferrer"><MessageCircle size={19} /> واتساب مباشر</a><a href="tel:01142900066"><PhoneIcon /> 01142900066</a><span><MapPin size={19} /> بلوك 11 الحرفيين — السلام، القاهرة</span></div></div><div className="map-card"><MapPin size={34} /><strong>موقع المخزن</strong><span>الحرفيين · السلام · القاهرة</span><a className="button button-primary" href={whatsapp("أريد معرفة موقع المخزن ومواعيد العمل") } target="_blank" rel="noreferrer">احصل على الاتجاهات</a></div></div></PageSection></StoreLayout>; }
function PhoneIcon() { return <span aria-hidden="true">☎</span>; }

export function FaqPage() { const faqs = [["هل كل القطع أصلية؟", "نعرض قطعًا من مصادر موثقة مثل غبور وموبيس، ونوضح المصدر داخل بطاقة المنتج."], ["هل أحتاج رقم الشاسيه؟", "نعم، نستخدم VIN لتأكيد المطابقة النهائية قبل تجهيز الطلب والشحن."], ["هل تشحنون خارج القاهرة؟", "نعم، نوصل لجميع المحافظات ويتم تحديد تكلفة الشحن عند تأكيد الطلب."], ["هل يوجد استبدال أو استرجاع؟", "يتم قبول الطلبات وفق حالة القطعة وسياسة الاستبدال الموضحة مع فريق المبيعات."]]; return <StoreLayout title="الأسئلة الشائعة" eyebrow="09 / قبل ما تطلب"><PageSection><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></PageSection></StoreLayout>; }

export function ModelPage() { const [, params] = useRoute<{ model: string }>("/models/:model"); const model = decodeURIComponent(params?.model ?? "توسان"); const matching = parts.filter((part) => part.model === model); return <StoreLayout title={`قطع غيار ${model}`} eyebrow="10 / صفحات الموديلات"><PageSection><SectionTitle eyebrow="دليل الموديل" title={`قطع ${model} الأصلية`} copy="اختار نوع القطعة أو ابحث برقم OEM. تأكيد المطابقة يتم عبر VIN قبل الشحن." /><div className="model-facts"><span><CarFront size={18} /> هيونداي وكيا</span><span><ShieldCheck size={18} /> مطابقة الشاسيه</span><span><Truck size={18} /> شحن لكل المحافظات</span></div><ProductGrid items={matching.length ? matching : parts} /></PageSection></StoreLayout>; }

function PolicyPage({ kind }: { kind: "shipping" | "returns" | "privacy" }) { const content = kind === "shipping" ? ["الشحن والتوصيل", "نجهز الطلب بعد مراجعة رقم الشاسيه وتأكيد التوفر. يتم التواصل معك لتحديد عنوان التسليم وتكلفة الشحن حسب المحافظة."] : kind === "returns" ? ["الاستبدال والاسترجاع", "يتم فحص القطعة قبل الشحن. في حالة وجود مشكلة في المطابقة أو عيب مصنعي، تواصل مع فريق المبيعات فور الاستلام لتقييم الحالة."] : ["الخصوصية", "نستخدم بيانات التواصل ورقم الشاسيه فقط لتأكيد المطابقة وتنفيذ الطلب. لا يتم إرسال VIN إلى أدوات التحليلات العامة."]; return <StoreLayout title={content[0]} eyebrow="11 / معلومات مهمة"><PageSection><article className="policy-card"><div className="auth-icon"><ShieldCheck size={24} /></div><h2>{content[0]}</h2><p>{content[1]}</p><h3>تحتاج مساعدة؟</h3><a className="button button-primary" href={whatsapp(`مرحباً، لدي استفسار عن ${content[0]}`)} target="_blank" rel="noreferrer">تحدث مع فريق المبيعات <MessageCircle size={17} /></a></article></PageSection></StoreLayout>; }
export const ShippingPage = () => <PolicyPage kind="shipping" />;
export const ReturnsPage = () => <PolicyPage kind="returns" />;
export const PrivacyPage = () => <PolicyPage kind="privacy" />;
